<div class="container container-archive">
    <header>
        <h1>Poster Archive</h1>
        <ul class="nav nav-pills">
            <?php foreach ($index as $folder): ?>
                <li class="<?php if(strpos($path, $folder['path']) === 0) echo 'active'; ?>" role="presentation">
                    <a href="?path=<?= urlencode($folder['path']) ?>"><?= escape($folder['basename']) ?></a>
                </li>
            <?php endforeach ?>
        </ul>
    </header>
    <ul class="list-unstyled archive">
        <?php foreach ($posters as $item): ?>
            <?php if ($item['type'] === 'file'): ?>
                <li>
                    <a href="?poster=<?= urlencode($item['path']) ?>" target="_blank" class="poster">
                        <img src="?poster=<?= urlencode($item['path']) ?>&view=thumbnail" alt=".<?= $item['extension'] ?>-file">
                        <span class="name"><?= escape($item['filename']) ?></span>
                    </a>
                </li>
            <?php else: ?>
                <li>
                    <a href="?path=<?= urlencode($item['path']) ?>" class="folder">
                        <span class="icon"><i class="fa fa-folder-open-o" aria-hidden="true"></i></span>
                        <span class="name"><?= escape($item['basename']) ?></span>                        
                    </a>
                </li>
            <?php endif ?>
        <?php endforeach ?>
    </ul>
    <footer class="text-center">
       <p>
           Copyright on all posters on this website belongs to their respective authors. Please contact the <a href="mailto:publicitee@svcover.nl">PubliciTee</a> for more information.
       </p>
    </footer>
</div>
