<!DOCTYPE html>
<html>
    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="mobileoptimized" content="0">
        <title><?= $title ?> &mdash; PubliciTee Cover</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" type="text/css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" type="text/css">
        <link rel="stylesheet" href="//cdl.svcover.nl/dist/v0.1/css/cdl.css" type="text/css">
        <link rel="stylesheet" href="/static/css/bootstrap-datetimepicker.min.css">
        <link rel="stylesheet" href="/static/css/publicitee.css">
    </head>
    <body>
        <nav class="navbar navbar-cover">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-logo" href="//www.svcover.nl/"><img src="//cdl.svcover.nl/dist/v0.1/img/cover.png" alt="Cover"></a>
                    <a class="navbar-brand" href="/">PubliciTee</a>
                </div>
                <!-- Toggleable content -->
                <div class="collapse navbar-collapse" id="navbar-demo-collapse">
                    <ul class="navbar-right">
                        <li class="<?= $this->get_menu_status('request') ?>"><a href="/">Request</a></li>
                        <li class="<?= $this->get_menu_status('archive') ?>"><a href="/archive.php">Archive</a></li>
                        <!-- Dropdown menu -->
                        <?php if(!get_cover_session()): ?>
                            <li><a href="<?= cover_login_url() ?>">Log in</a></li>
                        <?php else: ?>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa fa-angle-down"></i>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="dropdown-header">Logged in as <?= get_cover_session()->voornaam ?></li>
                                    <li><a href="<?= cover_logout_url() ?>">Logout</a></li>
                                </ul>
                            </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </nav>
        <?= $content ?>
        <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        <!-- <script src="js/moment.js"></script> -->
        <!-- <script src="js/bootstrap-datetimepicker.min.js"></script> -->
    </body>
</html>
