<div class="container container-narrow">
    <header>
        <h1>Poster Request Form</h1>
        <p>
            You can use this form to request posters for your activities. Please keep in mind that posters need to be requested at least three weeks before the activity. We will then make sure the poster will be printed and distributed within a week. Please contact the <a href="mailto:propagandee@svcover.nl">PropaganDee</a> if you have further questions or non-standard request.
        </p>
    </header>
    <?= $content ?>
</div>
